"""Deterministic LaTeX projection of a structured ModelSpec mathematics block."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tabu_lab.registry import ModelSpec


_TEX_TEXT_REPLACEMENTS = (
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
)


def _text(value: object) -> str:
    rendered = str(value)
    for source, replacement in _TEX_TEXT_REPLACEMENTS:
        rendered = rendered.replace(source, replacement)
    return rendered


def _ref(value: str) -> str:
    return "id-" + value.encode("utf-8").hex()


def _itemize(items: list[str]) -> str:
    if not items:
        return ""
    body = "\n".join(f"  \\item {_text(item)}" for item in items)
    return f"\\begin{{itemize}}\n{body}\n\\end{{itemize}}\n"


def render_model_tex(spec: ModelSpec) -> str:
    """Render a ModelSpec's mathematical contract as a standalone TeX document.

    This is a projection, not a second semantic authority.  A contract without a
    structured ``mathematics`` block fails closed so a generated document cannot imply
    that free-form metadata is already a complete derivation.
    """

    mathematics = spec.mathematics
    if mathematics is None:
        raise ValueError(
            f"model {spec.contract_id!r} has no structured mathematics block; "
            "add `mathematics` before rendering TeX"
        )

    contract_id = _text(spec.contract_id)
    contract_version = _text(spec.contract_version)
    maturity_stage = _text(spec.maturity.stage.value)
    build_state = _text(spec.maturity.build_state.value)
    carrier_declaration = _text(
        spec.carrier.get("shape", "shape is specified in the carrier contract")
    )
    dynamics_declaration = _text(
        spec.dynamics.get("family", "dynamics family is specified in the contract")
    )
    readout_declaration = _text(
        spec.readout.get("geometry", "readout geometry is specified in the contract")
    )
    loss_declaration = _text(
        spec.loss.get("truth_entry", "truth entry is specified in the loss contract")
    )

    lines = [
        "% Generated by `tabu-lab models render-tex`; edit the ModelSpec YAML, not this file.",
        "% The generated document is a readable projection, not evidence or a maturity promotion.",
        "% !TEX program = xelatex",
        r"\documentclass[11pt,a4paper,fontset=mac]{ctexart}",
        r"\usepackage[margin=2.45cm]{geometry}",
        r"\usepackage{amsmath,amssymb,mathtools,bm}",
        r"\usepackage{booktabs,tabularx,array}",
        r"\usepackage{enumitem}",
        r"\usepackage{xcolor}",
        r"\usepackage{hyperref}",
        r"\hypersetup{colorlinks=true,linkcolor=blue!45!black,urlcolor=blue!55!black}",
        r"\setlength{\parindent}{2em}",
        r"\setlength{\parskip}{0.32em}",
        r"\setlength{\emergencystretch}{3em}",
        r"\pagestyle{plain}",
        r"\setlist[itemize]{leftmargin=2em,itemsep=0.2em,topsep=0.3em}",
        r"\setlist[enumerate]{leftmargin=2.2em,itemsep=0.25em,topsep=0.3em}",
        "",
        rf"\title{{\textbf{{{_text(spec.display_name)}}}\\[4pt]",
        r"\large Generated mathematical contract}",
        r"\author{TabU model-factory}",
        r"\date{contract " + contract_id + r" · version " + contract_version + "}",
        "",
        r"\begin{document}",
        r"\maketitle",
        "",
        r"\begin{abstract}",
        _text(mathematics.abstract),
        r"\end{abstract}",
        "",
        r"\section{Contract identity and scope}",
        rf"This document is generated from the \texttt{{ModelSpec}} contract ``{contract_id}'' "
        rf"version ``{contract_version}''. ",
        rf"Its current stage is \texttt{{{maturity_stage}}} and "
        rf"its build state is \texttt{{{build_state}}}. ",
        "The generated TeX explains the declared mathematics; it does not create an "
        "implementation, a trained checkpoint, an execution receipt, or an accepted claim.",
        "",
        rf"\textbf{{Semantic Unit statement.}} {_text(mathematics.unit_semantics)}",
        "",
        r"\section{Notation}",
        r"\begin{tabularx}{\textwidth}{>{$}l<{$} "
        r">{\raggedright\arraybackslash}p{0.25\textwidth} X}",
        r"\toprule",
        r"Symbol & Domain & Meaning \\",
        r"\midrule",
    ]
    for symbol in mathematics.notation:
        domain = rf"\({symbol.domain}\)" if symbol.domain is not None else "--"
        lines.append(f"{symbol.symbol} & {domain} & {_text(symbol.meaning)} " + r"\\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabularx}",
            "",
            r"\section{Ordered mathematical construction}",
            "The stages below are ordered.  Each equation is named so that future "
            "conformance tests and source reviews can refer to the same object.",
            "",
        ]
    )
    for index, step in enumerate(mathematics.steps, start=1):
        lines.extend(
            [
                rf"\subsection{{Step {index}: {_text(step.title)}}}",
                _text(step.purpose),
            ]
        )
        for equation in step.equations:
            lines.extend(
                [
                    rf"\begin{{equation}}\label{{eq:{_ref(equation.id)}}}",
                    equation.latex,
                    r"\end{equation}",
                    rf"\textbf{{Meaning.}} {_text(equation.meaning)}",
                    "",
                ]
            )
        if step.invariants:
            lines.extend([r"\paragraph{Stage invariants.}", _itemize(list(step.invariants))])

    lines.extend(
        [
            r"\section{Falsifiable invariants}",
            "The following statements are part of the contract's mathematical "
            "boundary.  They require the evidence named in the YAML; their presence "
            "here is not evidence that they have passed.",
        ]
    )
    for invariant in mathematics.invariants:
        lines.extend(
            [
                rf"\subsection{{{_text(invariant.id)}}}",
                _text(invariant.statement),
                rf"\textbf{{Evidence target.}} {_text(invariant.evidence)}",
                "",
            ]
        )

    lines.extend(
        [
            r"\section{Implementation and evidence boundary}",
            rf"The carrier declares: {carrier_declaration}.",
            rf" The dynamics declares: {dynamics_declaration}.",
            rf" The readout declares: {readout_declaration}.",
            rf" The loss boundary declares: {loss_declaration}.",
            "",
            r"\paragraph{Open questions.}",
            _itemize([item.question for item in spec.known_open]),
            r"\paragraph{Kill conditions.}",
            _itemize([f"{gate.condition} (evidence: {gate.evidence})" for gate in spec.kill]),
            r"\paragraph{Exit conditions.}",
            _itemize([f"{gate.condition} (evidence: {gate.evidence})" for gate in spec.exit]),
            "",
            r"\section{Provenance note}",
            rf"The upstream reference is \texttt{{{_text(spec.upstream.repository)}}} "
            rf"at \texttt{{{_text(spec.upstream.path)}}}; its recorded SHA-256 is "
            rf"\texttt{{{_text(spec.upstream.sha256)}}}. ",
            "The YAML ModelSpec remains the semantic source for this projection.  "
            "Edit the YAML and regenerate the TeX when the contract changes.",
            "",
            r"\end{document}",
            "",
        ]
    )
    return "\n".join(lines)
