from __future__ import annotations

import json

import pytest

import tabu_lab.cli as cli_module
from tabu_lab.cli import main


def test_models_list_json_is_stable(capsys) -> None:
    assert main(["models", "list", "--json"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert [item["contract_id"] for item in payload] == sorted(
        [
            "tabufl",
            "tabul",
            "tabuf",
            "tabu4rec",
            "tabu4graph",
            "tabu4do",
            "tabu.unit_row",
            "tabu.unit_pair",
            "tabu.cell.base",
            "tabu.cell.column",
            "tabu.cell.rec",
            "tabu.cell.row",
            "tabu.cell.row_column",
        ]
    )
    do = next(item for item in payload if item["contract_id"] == "tabu4do")
    assert do["build_state"] == "design_open"


def test_models_show_json(capsys) -> None:
    assert main(["models", "show", "tabuf", "--json"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["contract_id"] == "tabuf"
    assert payload["upstream"]["readonly"] is True
    assert len(payload["upstream"]["sha256"]) == 64


def test_models_list_and_show_use_catalog_not_the_packaged_registry(
    capsys,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def unexpected_registry_read(*args, **kwargs):
        raise AssertionError("catalog-backed inspection must not read the source registry")

    monkeypatch.setattr(cli_module, "list_models", unexpected_registry_read)
    monkeypatch.setattr(cli_module, "get_model_spec", unexpected_registry_read)

    assert main(["models", "list", "--json"]) == 0
    assert json.loads(capsys.readouterr().out)
    assert main(["models", "show", "tabuf", "--json"]) == 0
    assert json.loads(capsys.readouterr().out)["contract_id"] == "tabuf"


def test_models_validate_without_upstream(capsys) -> None:
    assert main(["models", "validate", "--skip-upstream", "--json"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload == {
        "checked": sorted(
            [
                "tabufl",
                "tabul",
                "tabuf",
                "tabu4rec",
                "tabu4graph",
                "tabu4do",
                "tabu.unit_row",
                "tabu.unit_pair",
                "tabu.cell.base",
                "tabu.cell.column",
                "tabu.cell.rec",
                "tabu.cell.row",
                "tabu.cell.row_column",
            ]
        ),
        "issues": [],
        "ok": True,
    }


def test_unknown_model_is_nonzero(capsys) -> None:
    assert main(["models", "show", "not-a-model", "--json"]) == 2
    assert "unknown model contract" in capsys.readouterr().err


def test_models_render_tex_writes_standalone_projection(tmp_path, capsys) -> None:
    output = tmp_path / "tabuf.generated.tex"

    assert main(["models", "render-tex", "tabuf", "--output", str(output)]) == 0

    assert output.is_file()
    assert "wrote:" in capsys.readouterr().out
    rendered = output.read_text(encoding="utf-8")
    assert rendered.startswith("% Generated by `tabu-lab models render-tex`")
    assert r"\section{Ordered mathematical construction}" in rendered
